### ISSUE TITLE
"ADB IDEA: No Device found" on Android Studio Arctic Fox | 2020.3.1 Canary 12

### ISSUE THREAD

**Issue by Egorand** [pbreault/adb-idea#131]
**Environment:**

Android Studio Arctic Fox | 2020.3.1 Canary 12
Build #AI-203.7148.57.2031.7226969, built on March 22, 2021
Runtime version: 11.0.8+10-b944.6842174 x86_64
VM: OpenJDK 64-Bit Server VM by N/A
macOS 10.16
GC: G1 Young Generation, G1 Old Generation
Memory: 8096M
Cores: 12

**Steps to repro:**

1. Open the plugin menu with Ctrl + Shift + A.
2. Select "Clear App Data".
3. The action is not executed.

**Event log printout:**

```
11:56 a.m.	ADB IDEA: No platform configured

11:56 a.m.	ADB IDEA: No Device found
```

**Stacktrace from `idea.log`:**

```
2021-03-31 11:54:58,094 [1547083]  ERROR - pplication.impl.LaterInvocator - 'com.intellij.util.ThreeState com.android.tools.idea.run.LaunchCompatibility.isCompatible()' 
java.lang.NoSuchMethodError: 'com.intellij.util.ThreeState com.android.tools.idea.run.LaunchCompatibility.isCompatible()'
	at com.developerphil.adbidea.ui.MyDeviceChooser$LaunchCompatibilityRenderer.customizeCellRenderer(MyDeviceChooser.kt:306)
	at com.intellij.ui.ColoredTableCellRenderer.rendererComponentInner(ColoredTableCellRenderer.java:58)
	at com.intellij.ui.ColoredTableCellRenderer.getTableCellRendererComponent(ColoredTableCellRenderer.java:41)
	at com.intellij.ui.table.JBTable.calculateRowHeight(JBTable.java:233)
	at com.intellij.ui.table.JBTable.getRowHeight(JBTable.java:211)
	at java.desktop/javax.swing.JTable.getRowHeight(JTable.java:1007)
	at java.desktop/javax.swing.JTable.getCellRect(JTable.java:2926)
	at java.desktop/javax.swing.JTable.valueChanged(JTable.java:4703)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:219)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:199)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:246)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:443)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:453)
	at java.desktop/javax.swing.DefaultListSelectionModel.removeSelectionIntervalImpl(DefaultListSelectionModel.java:614)
	at java.desktop/javax.swing.DefaultListSelectionModel.clearSelection(DefaultListSelectionModel.java:458)
	at java.desktop/javax.swing.JTable.clearSelection(JTable.java:2124)
	at java.desktop/javax.swing.JTable.clearSelectionAndLeadAnchor(JTable.java:2132)
	at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4375)
	at java.desktop/javax.swing.JTable.setModel(JTable.java:3693)
	at com.intellij.ui.table.JBTable.setModel(JBTable.java:340)
	at com.developerphil.adbidea.ui.MyDeviceChooser.refreshTable(MyDeviceChooser.kt:179)
	at com.developerphil.adbidea.ui.MyDeviceChooser.access$refreshTable(MyDeviceChooser.kt:59)
	at com.developerphil.adbidea.ui.MyDeviceChooser$updateTable$2.run(MyDeviceChooser.kt:164)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:828)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:330)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:828)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Happy to provide more debugging info.

**Comment by vaibhavvishal** [comment]
+1
Same issue and logs with Arctic Fox Beta 3

**Comment by BIGMONK** [comment]
+1
Same issue and logs with Arctic Fox | 2020.3.1 RC

**Comment by wp292519413** [comment]
I fixed the bug: https://github.com/wp292519413/adb-idea
latest adb-idea.zip: https://github.com/wp292519413/adb-idea/blob/master/adb_idea.zip

**Comment by BoGnY** [comment]
Fix not work on Android Studio Arctic Fox | 2020.3.1 Patch 2..

No error on `idea.log` but still get **ADB IDEA: No Device found**

**Comment by KatayR** [comment]
Alright, I figured out the problem. It works with native development but doesn't work with Flutter

**Comment by vanosidor** [comment]
Not works with Flutter (Android Studio Flamingo)

**Comment by hsm59** [comment]
If someone is still looking for ADB to work on Flutter projects - https://plugins.jetbrains.com/plugin/34312-flutter-adb
